"""fix_sqlite_schema

Revision ID: 733f9131075e
Revises: 64691d3a9534
Create Date: 2025-11-25 06:23:02.344931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733f9131075e'
down_revision: Union[str, None] = '64691d3a9534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add new columns
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conception_art', sa.Boolean(), nullable=True, default=False))
        batch_op.add_column(sa.Column('bmi', sa.Float(), nullable=True))

    # Step 2: Alter existing column (separate context to avoid circular dependency bug)
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.alter_column('gestational_age_weeks',
                   existing_type=sa.INTEGER(),
                   type_=sa.Float(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.alter_column('gestational_age_weeks',
                   existing_type=sa.Float(),
                   type_=sa.INTEGER(),
                   existing_nullable=True)
        batch_op.drop_column('bmi')
        batch_op.drop_column('conception_art')
    # ### end Alembic commands ###
